name: vault_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info_plus: ^4.2.0

  # Firebase
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.0.1
  go_router_builder: ^2.6.0
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
flutter:
  uses-material-design: true
