name: flutter-ci

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
  workflow_dispatch:

jobs:
  flutter-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Code analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test
